# Generated by Django 4.2 on 2023-06-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='link',
        ),
    ]
