# Generated by Django 4.2 on 2023-06-28 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='pins',
            field=models.ManyToManyField(blank=True, related_name='pins', to='pins.pin'),
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to=settings.AUTH_USER_MODEL),
        ),
    ]
